import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Interview Questions Generator - Custom Prep | DecaJobs",
  description: "Prepare for your next job interview with tailored questions generated by AI. Get role-specific questions and expert model answers.",
  alternates: {
    canonical: "/tools/interview-questions",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
